name: 'Unity Cloud Build Action'
description: 'Allows to start a build on Unity Cloud Build, and await its result'
author: 'Elmar Jansen'
branding:
  icon: 'cloud-snow'
  color: 'black'
inputs:
  orgId: 
    required: true
    description: 'Organization ID'
  projectId:
    required: true
    description: 'Project ID'
  repoUrl:
    required: true
    description: 'The repo url to use for the Unity project'
  gitRef:
    required: true
    description: 'Target Git Ref, e.g. /refs/heads/main'
  gitSha:
    required: true
    description: 'Target Git commit SHA'
  subdirectoryPath:
    required: false
    default: ''
    description: 'The subdirectory that is the root of the Unity project'
  buildTargetId:
    required: false
    default: ''
    description: 'Build Target ID'
  apiKey:
    required: true
    description: 'Unity Cloud Build API key'
runs:
  using: 'node12'
  main: 'dist/index.js'
