name: Build Gemini
on:
  push:
    branches:
    - master
    - develop
    - prod
jobs:
  build:
    uses: ./.github/workflows/build-unity-project.yml
    name: Build and Publish Gemini
    with:
      cloud-build-org-id: '20066671868386'
      cloud-build-project-id: 7e50c94f-4652-4d58-bc5b-d36dcfa8ab62
      project-subdirectory: empty-test-proj
      project-name: gemini
      environment: action-runner-env
      runs-on: wsl
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
      aws-region: us-east-2
  publish:
    uses: ./.github/workflows/publish-unity-project.yml
    needs: build
    name: Publish Gemini
    with:
      staging-dir-path: ${{ needs.build.outputs.staging-dir-path }}
      environment: action-runner-env
      runs-on: wsl
    secrets:
      unity-cloud-build-api-key: ${{ secrets.UNITY_CLOUD_BUILD_API_KEY }}

