name: Build and Publish Gemini
on:
  push:
    branches:
    - master
    - develop
    - prod
  pull_request: {}
jobs:
  run-cloud-build:
    runs-on: wsl
    environment: action-runner-env
    steps:
      - uses: actions/checkout@v2
      - id: cloud-build
        uses: ./.github/actions/unity-cloud-build/runBuild
        with:
          orgId: 20066671868386
          projectId: 7e50c94f-4652-4d58-bc5b-d36dcfa8ab62
          apiKey: ${{ secrets.UNITY_CLOUD_BUILD_API_KEY }}
          repoUrl: ${{ github.repositoryUrl }}
          gitRef: ${{ github.head_ref || github.ref }}
          gitSha: ${{ github.event.pull_request.head.sha || github.context.sha }}
          subdirectoryPath: 'empty-test-proj'
      - id: stage-files
        uses: ./.github/actions/unity-cloud-build/stageFiles
        if: ${{ success() }}
        with:
          projectName: default-webgl
          artifactUrl: ${{ steps.cloud-build.outputs.downloadUrl }}
      - id: publish-to-s3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: ${{ steps.stage-files.outputs.stagingDirPath }}
          DEST_DIR: "gemini-${{ github.event.pull_request.head.sha || github.context.sha }}"
