name: PR Validate
on:
  push:
    branches:
    - master
    - develop
    - prod
  pull_request: {}
jobs:
  start-cloud-build:
    runs-on: wsl
    environment: action-runner-env
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/unity-cloud-build-action
        with:
          orgId: 20066671868386
          projectId: 7e50c94f-4652-4d58-bc5b-d36dcfa8ab62
          apiKey: ${{ secrets.UNITY_CLOUD_BUILD_API_KEY }}
          repoUrl: ${{ github.repositoryUrl }}
          gitRef: ${{ github.head_ref || github.ref }}
          gitSha: ${{ github.event.pull_request.head.sha || github.context.sha }}
          subdirectoryPath: 'empty-test-proj'
